import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";
export const metadata: Metadata = { title: "Privacy policy" };
export default function PrivacyPage() { return <LegalPage title="Privacy policy" intro="This policy explains what echoglitch collects, why it is used, who processes it, and the choices available to you." sections={[
  { title: "Information we collect", paragraphs: ["We collect information you provide when you contact us, join a waitlist, place an order, or use an administrative account."], bullets: ["Name, email address, consent record, and the message or goal you submit.", "Order references, product, amount, payment status, and fulfilment history. We do not store complete card, UPI PIN, or banking credentials.", "Basic security and diagnostic data such as IP-derived abuse signals, timestamps, browser metadata, and server logs."] },
  { title: "Why we use it", paragraphs: ["We use personal data to respond to requests, deliver purchased products, send operational messages, manage pre-orders and waitlists, prevent abuse, comply with law, and improve our products. Marketing updates are sent only where you have consented or where otherwise permitted, and every marketing message includes an unsubscribe route."] },
  { title: "Who processes it", paragraphs: ["We use service providers to run the platform: Cloudflare for delivery and security, Supabase for database and authentication services, Razorpay for payments, and Resend for transactional email. Each provider receives only the information needed for its role and may process data in other countries under its own safeguards."] },
  { title: "Retention", paragraphs: ["Lead and waitlist records are reviewed at least annually and removed when they are no longer needed or consent is withdrawn. Order and tax records may be retained for the period required by applicable accounting, tax, fraud-prevention, and consumer laws. Security logs are kept for a limited operational period unless an incident requires longer preservation."] },
  { title: "Your choices and rights", paragraphs: ["You may ask for access, correction, deletion, withdrawal of consent, or information about how your data is handled. Withdrawal does not affect processing already carried out lawfully and may not require deletion of records that must be kept by law. You may also nominate or use any grievance rights available under applicable Indian data-protection law."] },
  { title: "Security and children", paragraphs: ["We use access controls, encryption in transit, least-privilege credentials, payment-signature checks, and monitoring appropriate to this service. No online system can promise absolute security. echoglitch is not directed to children under 18, and we do not knowingly collect their personal data without appropriate authorisation."] },
]} />; }
