"use client";
import { useState } from "react";
import { LogOut, RefreshCw, Save } from "lucide-react";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type Product = { id: string; title: string; slug: string; price: number; status: string; release_at: string | null; file_path: string | null };
export function AdminDashboard({ initialProducts, metrics, email }: { initialProducts: Product[]; metrics: { orders: number; revenue: number; leads: number; waitlist: number }; email: string }) {
  const [products, setProducts] = useState(initialProducts); const [message, setMessage] = useState(""); const [busy, setBusy] = useState("");
  function update(id: string, field: keyof Product, value: string | number) { setProducts((items) => items.map((item) => item.id === id ? { ...item, [field]: value } : item)); }
  async function save(product: Product) { setBusy(product.id); setMessage(""); const response = await fetch("/api/admin/playbooks", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: product.id, price: product.price, status: product.status, release_at: product.release_at }) }); setMessage(response.ok ? `${product.title} saved.` : "The update failed. Check the integration and try again."); setBusy(""); }
  async function logout() { await fetch("/api/admin/session", { method: "DELETE" }); window.location.href = "/admin/login"; }
  return <div className="admin-shell"><aside className="admin-sidebar"><a className="brand" href="/"><span className="brand-mark">e</span><span>echoglitch</span></a><div><span>Signed in as</span><strong>{email}</strong></div><button onClick={logout}><LogOut size={17} />Sign out</button></aside><main className="admin-main"><header><div><p>Operations</p><h1>Flight deck</h1></div><button onClick={() => window.location.reload()}><RefreshCw size={17} />Refresh</button></header><section className="metric-grid"><article><span>Paid orders</span><strong>{metrics.orders}</strong></article><article><span>Revenue</span><strong>₹{(metrics.revenue/100).toLocaleString("en-IN")}</strong></article><article><span>Lead signals</span><strong>{metrics.leads}</strong></article><article><span>Waitlist</span><strong>{metrics.waitlist}</strong></article></section><section className="admin-panel"><div className="admin-panel-heading"><div><p>Catalogue</p><h2>Playbook release controls</h2></div>{message && <span role="status">{message}</span>}</div><Table><TableHeader><TableRow><TableHead>Playbook</TableHead><TableHead>Status</TableHead><TableHead>Price (paise)</TableHead><TableHead>Release</TableHead><TableHead>Asset</TableHead><TableHead><span className="sr-only">Save</span></TableHead></TableRow></TableHeader><TableBody>{products.map((product) => <TableRow key={product.id}><TableCell><strong>{product.title}</strong><small>{product.slug}</small></TableCell><TableCell><select value={product.status} onChange={(event) => update(product.id, "status", event.target.value)}><option value="draft">Draft</option><option value="available">Available</option><option value="preorder">Pre-order</option><option value="waitlist">Waitlist</option></select></TableCell><TableCell><input type="number" min="0" value={product.price} onChange={(event) => update(product.id, "price", Number(event.target.value))} /></TableCell><TableCell><input type="date" value={product.release_at?.slice(0,10) || ""} onChange={(event) => update(product.id, "release_at", event.target.value)} /></TableCell><TableCell>{product.file_path ? "Ready" : "Missing"}</TableCell><TableCell><button className="save-button" onClick={() => save(product)} disabled={busy === product.id}><Save size={16} />{busy === product.id ? "Saving" : "Save"}</button></TableCell></TableRow>)}</TableBody></Table></section></main></div>;
}
