import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";
export const metadata: Metadata = { title: "Terms of use" };
export default function TermsPage() { return <LegalPage title="Terms of use" intro="These terms govern use of echoglitch.in and purchases of echoglitch digital products. By using the site or completing an order, you agree to them." sections={[
  { title: "The service", paragraphs: ["echoglitch provides educational content, downloadable playbooks, templates, and related digital tools. Content is general information, not legal, financial, medical, tax, or other regulated professional advice. Results depend on your situation and effort; no particular outcome is guaranteed."] },
  { title: "Orders and payment", paragraphs: ["Prices are shown in Indian rupees. Applicable taxes will be disclosed in the checkout or invoice. Payments are processed by Razorpay. An order is accepted when payment is verified and we send a fulfilment confirmation. We may cancel and refund an order affected by pricing, availability, fraud, or technical errors."] },
  { title: "Pre-orders", paragraphs: ["A pre-order reserves the listed product at the displayed price. Estimated release dates may change if additional work is needed. If a material delay occurs, we will notify the purchaser and provide a reasonable cancellation option before delivery."] },
  { title: "Licence", paragraphs: ["A purchase grants one individual a personal, non-exclusive, non-transferable licence to use the delivered files and templates. You may adapt templates for your own work. You may not resell, publicly distribute, share access at scale, remove rights notices, or use the materials to train or assemble a competing product without written permission."] },
  { title: "Acceptable use", paragraphs: ["Do not probe security controls, automate abusive requests, upload malicious content, impersonate another person, interfere with payment or fulfilment systems, or use the site in violation of law. We may restrict access to protect users or the service."] },
  { title: "Liability and governing law", paragraphs: ["To the extent permitted by law, echoglitch is not liable for indirect or consequential loss arising from use of educational materials. Our aggregate liability for a purchased digital product will not exceed the amount paid for that product, except where law does not allow such a limit. These terms are governed by the laws of India; mandatory consumer rights and any court jurisdiction required by law remain unaffected."] },
]} />; }
